export const customInput = {
	base: '!no-underline text-gray-700',
	label: 'text-gray-700',
	input: [
		'bg-transparent',
		'text-gray-700/90',
		'placeholder:text-gray-700/25',
		'!no-underline',
	],
	innerWrapper: 'bg-transparent !no-underline !text-gray-700',
	inputWrapper: [
		'shadow-none',
		'border',
		'border-cyan-900/25',
		'bg-gray-50',
		'hover:bg-gray-100',
		'group-data-[focused=true]:bg-gray-200',
		'!cursor-text',
	],
	trigger: [
		'shadow-none',
		'border',
		'border-cyan-900/25',
		'bg-gray-50',
		'hover:bg-gray-100',
		'group-data-[focused=true]:bg-gray-200',
		'!cursor-text',
		'!no-underline',
		'text-gray-700/90',
	],
}
